import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

const PLAN_GATE = ['pro', 'agency']

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  const cookieStore = cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll() },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          )
        },
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new Response('Unauthorized', { status: 401 })

  const { data: profile } = await supabase
    .from('profiles')
    .select('subscription_status, full_name')
    .eq('id', user.id)
    .single()

  if (!PLAN_GATE.includes(profile?.subscription_status || 'free')) {
    return Response.json(
      { error: 'Accessibility Statement requires Pro or Agency plan' },
      { status: 403 }
    )
  }

  const { data: report } = await supabase
    .from('reports')
    .select('*, scans(*)')
    .eq('id', params.id)
    .eq('user_id', user.id)
    .single()

  if (!report) return new Response('Not found', { status: 404 })

  const scan = report.scans as any
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  const remainingIssues = scan.total_violations > 0
    ? `We have identified ${scan.total_violations} remaining issue${scan.total_violations > 1 ? 's' : ''} through automated testing, which our team is actively working to resolve.`
    : 'Our most recent automated scan found no outstanding issues.'

  const statementHtml = `<!-- Accessibility Statement — Generated by WCAG Scanner on ${today} -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Accessibility Statement — ${scan.url || ''}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a2e; background: #f8f9fa; padding: 40px 20px; }
    .container { max-width: 720px; margin: 0 auto; background: #fff; border-radius: 12px; padding: 48px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    h2 { font-size: 28px; font-weight: 700; margin-bottom: 8px; }
    h3 { font-size: 18px; font-weight: 600; margin: 28px 0 10px; }
    p { font-size: 15px; line-height: 1.7; color: #374151; margin-bottom: 14px; }
    ul { margin: 0 0 14px 20px; }
    li { font-size: 15px; line-height: 1.7; color: #374151; }
    strong { color: #111827; }
    .meta { font-size: 13px; color: #6b7280; margin-top: 32px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
    .score-badge { display: inline-block; background: #f3f4f6; padding: 4px 12px; border-radius: 6px; font-weight: 600; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <h2>Accessibility Statement</h2>
    <p>We are committed to ensuring digital accessibility for people of all abilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards.</p>

    <h3>Conformance Status</h3>
    <p>The Web Content Accessibility Guidelines (WCAG) define requirements for designers and developers to improve accessibility for people with disabilities. Our website has been evaluated against WCAG 2.1 Level AA using automated testing tools, including axe-core.</p>
    <p>As of <strong>${today}</strong>, our site achieved an automated compliance score of <strong>${scan.compliance_score}/100</strong>. ${remainingIssues}</p>

    <h3>Measures We Take</h3>
    <ul>
      <li>Regular automated accessibility scanning of our website</li>
      <li>Ongoing monitoring for newly introduced accessibility issues</li>
      <li>Prompt remediation of identified issues based on severity</li>
    </ul>

    <h3>Feedback</h3>
    <p>We welcome your feedback on the accessibility of our website. Please let us know if you encounter accessibility barriers by contacting us at <strong>[YOUR CONTACT EMAIL]</strong>.</p>

    <h3>Limitations</h3>
    <p>Despite our best efforts, automated testing tools detect approximately 57% of WCAG success criteria. Some issues may only be identified through manual testing. We are committed to identifying and fixing any remaining barriers as they are discovered.</p>

    <p><em>This statement was last reviewed on ${today} based on automated scan data and is updated as new scans are completed.</em></p>

    <p class="meta">Generated by WCAG Scanner — This statement reflects automated scan results and is not legal advice.</p>
  </div>
</body>
</html>`

  return new Response(statementHtml, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `attachment; filename="accessibility-statement-${params.id}.html"`,
    },
  })
}